travis:
  secure:
    BINSTAR_TOKEN: bdl2p+gnu7VoTC4nBwcVOzYSa727SQMmHhxhbAqgyuqrX8bDhHr25OjlVIXiI9Lqb4FdAD5tkjqd2L/lAHIoKy+FFUwgS11Tcw6fTkfNHWQk80gaI6WX58BbOaIk5BGV1mVijlfaNPb37IobILmFTMVuV4CI8QUjh1MJpDXAlBbMrqpm++WXwCTbpR5qK09n5JzfYwIR1HALaVQhEVKWpon1CYfNHtCeqXHKTTkN7zK7bBxeKksphSgiCjN8syLXqBFSIQElXW99MCGs0EzVjPh+/+2Y2SLbYLiqqv2G4LcdklQO88c1vUnOAhpydxvj2SHXLmzQh608ZrSIMf58xcKH1vvokPgF3arKOwu5vbPU4PFuwyWKBAadWu4mhJjykvPgS+l+KVGwkryyJwoEyboSZKygXG/U41KUwJXPxU42/FZr24AzjhM/PeuGIGNALEmbayEB4FnkxXUn+I79w9TIavvWE6VmIQTpJQsVaEi16obl5fxtzu53P1Dncq8T29WCm69iXUFgi75pMhlrlfKj53zzsrt3lcHD1YXeASc01eaKtIKnIzCv1dXtcp9K6Jq2qIHpYQLThz04OsLDWguilLk0V2twx6AUkH1aTAbEMQFR6RbwcJ5GNifLcJSHWORucpKC57v76FgpkzAYjZDKONEsj6Fkm2eq2FFNpIc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
